server:
  address:     "8200"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: false

database:
  default:
    link: "mysql:root:123456@tcp(8.134.148.139:3306)/test"
    prefix: "test_"
    debug: true

redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6379
    db:      0


