// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EbSystemAdmin is the golang structure of table eb_system_admin for DAO operations like Where/Data.
type EbSystemAdmin struct {
	g.Meta    `orm:"table:eb_system_admin, do:true"`
	Id        interface{} // ID
	Username  interface{} // 账号
	Realname  interface{} // 姓名
	Password  interface{} // 密码
	PicUrl    interface{} // 头像
	Status    interface{} // 状态 0未激活 1激活 2禁用
	UpdatedAt *gtime.Time // 更新时间
	CreatedAt *gtime.Time // 创建时间
}
