// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MuRabcRoleRoute is the golang structure of table mu_rabc_role_route for DAO operations like Where/Data.
type MuRabcRoleRoute struct {
	g.Meta    `orm:"table:mu_rabc_role_route, do:true"`
	Id        interface{} // ID
	RouteId   interface{} // 路由ID
	RoleId    interface{} // 角色ID
	Operator  interface{} // 操作人
	UpdatedAt *gtime.Time // 更新时间
	CreatedAt *gtime.Time // 创建时间
}
