// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MuRabcRoute is the golang structure of table mu_rabc_route for DAO operations like Where/Data.
type MuRabcRoute struct {
	g.Meta    `orm:"table:mu_rabc_route, do:true"`
	Id        interface{} // ID
	MenuId    interface{} // 菜单ID
	Name      interface{} // 名称
	Method    interface{} // 提交方式POST GET PUT DELETE
	Path      interface{} // 路径
	Status    interface{} // 是否隐藏菜单 0隐藏 1显示
	Sort      interface{} // 排序
	Operator  interface{} // 操作人
	UpdatedAt *gtime.Time // 更新时间
	CreatedAt *gtime.Time // 创建时间
}
