// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MuRabcMenus is the golang structure of table mu_rabc_menus for DAO operations like Where/Data.
type MuRabcMenus struct {
	g.Meta     `orm:"table:mu_rabc_menus, do:true"`
	Id         interface{} // 菜单ID
	Pid        interface{} // 父级id
	Icon       interface{} // 图标
	Title      interface{} // 名称
	Sort       interface{} // 排序
	IsShow     interface{} // 是否隐藏菜单 0隐藏 1显示
	Path       interface{} // 路径
	Operator   interface{} // 操作人
	UpdatedAt  *gtime.Time // 更新时间
	CreatedAt  *gtime.Time // 创建时间
	Header     interface{} // 名称
	IsHeader   interface{} // 名称
	UniqueAuth interface{} // 名称
}
