// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MuSystemAdmin is the golang structure of table mu_system_admin for DAO operations like Where/Data.
type MuSystemAdmin struct {
	g.Meta    `orm:"table:mu_system_admin, do:true"`
	Id        interface{} // ID
	Username  interface{} // 账号
	Phone     interface{} // 手机号码
	Password  interface{} // 密码
	Email     interface{} // 邮箱
	PicUrl    interface{} // 头像
	Status    interface{} // 状态 0未激活 1激活 2禁用 3删除
	UpdatedAt *gtime.Time // 更新时间
	CreatedAt *gtime.Time // 创建时间
}
