// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MuSystemConfig is the golang structure of table mu_system_config for DAO operations like Where/Data.
type MuSystemConfig struct {
	g.Meta    `orm:"table:mu_system_config, do:true"`
	Id        interface{} //
	TypeName  interface{} // 配置类型
	Name      interface{} // 名称
	Config    interface{} // 配置内容
	Operator  interface{} // 操作人
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
}
