// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// MuSystemMenus is the golang structure of table mu_system_menus for DAO operations like Where/Data.
type MuSystemMenus struct {
	g.Meta `orm:"table:mu_system_menus, do:true"`
	Id     interface{} // 菜单ID
	Pid    interface{} // 父级id
	Icon   interface{} // 图标
	Name   interface{} // 名称
	Sort   interface{} // 排序
	Status interface{} // 是否隐藏菜单 0隐藏 1显示
	Path   interface{} // 路径
}
