// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SystemMenus is the golang structure of table test_system_menus for DAO operations like Where/Data.
type SystemMenus struct {
	g.Meta     `orm:"table:test_system_menus, do:true"`
	Id         interface{} // 菜单ID
	Pid        interface{} // 父级id
	Icon       interface{} // 图标
	Title      interface{} // 名称
	Sort       interface{} // 排序
	IsShow     interface{} // 是否为隐藏菜单0=隐藏菜单,1=显示菜单
	Access     interface{} // 子管理员是否可用
	Path       interface{} // 路径
	UniqueAuth interface{} // 前台唯一标识
	IsDel      interface{} // 是否删除
	CreatedAt  *gtime.Time // 创建时间
	UpdatedAt  *gtime.Time // 更新时间
	Operator   interface{} // 操作人
}
