// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MuRabcMenusDao is the data access object for table mu_rabc_menus.
type MuRabcMenusDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns MuRabcMenusColumns // columns contains all the column names of Table for convenient usage.
}

// MuRabcMenusColumns defines and stores column names for table mu_rabc_menus.
type MuRabcMenusColumns struct {
	Id         string // 菜单ID
	Pid        string // 父级id
	Icon       string // 图标
	Title      string // 名称
	Sort       string // 排序
	IsShow     string // 是否隐藏菜单 0隐藏 1显示
	Path       string // 路径
	Operator   string // 操作人
	UpdatedAt  string // 更新时间
	CreatedAt  string // 创建时间
	Header     string // 名称
	IsHeader   string // 名称
	UniqueAuth string // 名称
}

// muRabcMenusColumns holds the columns for table mu_rabc_menus.
var muRabcMenusColumns = MuRabcMenusColumns{
	Id:         "id",
	Pid:        "pid",
	Icon:       "icon",
	Title:      "title",
	Sort:       "sort",
	IsShow:     "is_show",
	Path:       "path",
	Operator:   "operator",
	UpdatedAt:  "updated_at",
	CreatedAt:  "created_at",
	Header:     "header",
	IsHeader:   "is_header",
	UniqueAuth: "unique_auth",
}

// NewMuRabcMenusDao creates and returns a new DAO object for table data access.
func NewMuRabcMenusDao() *MuRabcMenusDao {
	return &MuRabcMenusDao{
		group:   "default",
		table:   "mu_rabc_menus",
		columns: muRabcMenusColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MuRabcMenusDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MuRabcMenusDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MuRabcMenusDao) Columns() MuRabcMenusColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MuRabcMenusDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MuRabcMenusDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MuRabcMenusDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
