// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MuRabcRouteDao is the data access object for table mu_rabc_route.
type MuRabcRouteDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns MuRabcRouteColumns // columns contains all the column names of Table for convenient usage.
}

// MuRabcRouteColumns defines and stores column names for table mu_rabc_route.
type MuRabcRouteColumns struct {
	Id        string // ID
	MenuId    string // 菜单ID
	Name      string // 名称
	Method    string // 提交方式POST GET PUT DELETE
	Path      string // 路径
	Status    string // 是否隐藏菜单 0隐藏 1显示
	Sort      string // 排序
	Operator  string // 操作人
	UpdatedAt string // 更新时间
	CreatedAt string // 创建时间
}

// muRabcRouteColumns holds the columns for table mu_rabc_route.
var muRabcRouteColumns = MuRabcRouteColumns{
	Id:        "id",
	MenuId:    "menu_id",
	Name:      "name",
	Method:    "method",
	Path:      "path",
	Status:    "status",
	Sort:      "sort",
	Operator:  "operator",
	UpdatedAt: "updated_at",
	CreatedAt: "created_at",
}

// NewMuRabcRouteDao creates and returns a new DAO object for table data access.
func NewMuRabcRouteDao() *MuRabcRouteDao {
	return &MuRabcRouteDao{
		group:   "default",
		table:   "mu_rabc_route",
		columns: muRabcRouteColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MuRabcRouteDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MuRabcRouteDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MuRabcRouteDao) Columns() MuRabcRouteColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MuRabcRouteDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MuRabcRouteDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MuRabcRouteDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
