// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MuRabcRoleRouteDao is the data access object for table mu_rabc_role_route.
type MuRabcRoleRouteDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns MuRabcRoleRouteColumns // columns contains all the column names of Table for convenient usage.
}

// MuRabcRoleRouteColumns defines and stores column names for table mu_rabc_role_route.
type MuRabcRoleRouteColumns struct {
	Id        string // ID
	RouteId   string // 路由ID
	RoleId    string // 角色ID
	Operator  string // 操作人
	UpdatedAt string // 更新时间
	CreatedAt string // 创建时间
}

// muRabcRoleRouteColumns holds the columns for table mu_rabc_role_route.
var muRabcRoleRouteColumns = MuRabcRoleRouteColumns{
	Id:        "id",
	RouteId:   "route_id",
	RoleId:    "role_id",
	Operator:  "operator",
	UpdatedAt: "updated_at",
	CreatedAt: "created_at",
}

// NewMuRabcRoleRouteDao creates and returns a new DAO object for table data access.
func NewMuRabcRoleRouteDao() *MuRabcRoleRouteDao {
	return &MuRabcRoleRouteDao{
		group:   "default",
		table:   "mu_rabc_role_route",
		columns: muRabcRoleRouteColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MuRabcRoleRouteDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MuRabcRoleRouteDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MuRabcRoleRouteDao) Columns() MuRabcRoleRouteColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MuRabcRoleRouteDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MuRabcRoleRouteDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MuRabcRoleRouteDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
