// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MuRabcAdminDao is the data access object for table mu_rabc_admin.
type MuRabcAdminDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns MuRabcAdminColumns // columns contains all the column names of Table for convenient usage.
}

// MuRabcAdminColumns defines and stores column names for table mu_rabc_admin.
type MuRabcAdminColumns struct {
	Id        string // ID
	Username  string // 账号
	Phone     string // 手机号码
	Password  string // 密码
	Email     string // 邮箱
	PicUrl    string // 头像
	Status    string // 状态 0未激活 1激活 2禁用 3删除
	Operator  string // 操作人
	UpdatedAt string // 更新时间
	CreatedAt string // 创建时间
}

// muRabcAdminColumns holds the columns for table mu_rabc_admin.
var muRabcAdminColumns = MuRabcAdminColumns{
	Id:        "id",
	Username:  "username",
	Phone:     "phone",
	Password:  "password",
	Email:     "email",
	PicUrl:    "pic_url",
	Status:    "status",
	Operator:  "operator",
	UpdatedAt: "updated_at",
	CreatedAt: "created_at",
}

// NewMuRabcAdminDao creates and returns a new DAO object for table data access.
func NewMuRabcAdminDao() *MuRabcAdminDao {
	return &MuRabcAdminDao{
		group:   "default",
		table:   "mu_rabc_admin",
		columns: muRabcAdminColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MuRabcAdminDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MuRabcAdminDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MuRabcAdminDao) Columns() MuRabcAdminColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MuRabcAdminDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MuRabcAdminDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MuRabcAdminDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
