// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SystemConfigDao is the data access object for table test_system_config.
type SystemConfigDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns SystemConfigColumns // columns contains all the column names of Table for convenient usage.
}

// SystemConfigColumns defines and stores column names for table test_system_config.
type SystemConfigColumns struct {
	Id        string // ID
	Name      string // 名称
	Type      string // 0json配置1基础配置2商城配置3用户配置
	Config    string // 配置
	Operator  string // 操作人
	CreatedAt string // 创建时间
	UpdatedAt string // 更新时间
}

// systemConfigColumns holds the columns for table test_system_config.
var systemConfigColumns = SystemConfigColumns{
	Id:        "id",
	Name:      "name",
	Type:      "type",
	Config:    "config",
	Operator:  "operator",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewSystemConfigDao creates and returns a new DAO object for table data access.
func NewSystemConfigDao() *SystemConfigDao {
	return &SystemConfigDao{
		group:   "default",
		table:   "test_system_config",
		columns: systemConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SystemConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SystemConfigDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SystemConfigDao) Columns() SystemConfigColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SystemConfigDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SystemConfigDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SystemConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
