// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SystemMenusDao is the data access object for table test_system_menus.
type SystemMenusDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns SystemMenusColumns // columns contains all the column names of Table for convenient usage.
}

// SystemMenusColumns defines and stores column names for table test_system_menus.
type SystemMenusColumns struct {
	Id         string // 菜单ID
	Pid        string // 父级id
	Icon       string // 图标
	Title      string // 名称
	Sort       string // 排序
	IsShow     string // 0隐藏1显示
	Status     string // 0关闭1开启
	Access     string // 子管理员是否可用
	Path       string // 路径
	UniqueAuth string // 前台唯一标识
	IsDel      string // 是否删除
	CreatedAt  string // 创建时间
	UpdatedAt  string // 更新时间
	Operator   string // 操作人
}

// systemMenusColumns holds the columns for table test_system_menus.
var systemMenusColumns = SystemMenusColumns{
	Id:         "id",
	Pid:        "pid",
	Icon:       "icon",
	Title:      "title",
	Sort:       "sort",
	IsShow:     "is_show",
	Status:     "status",
	Access:     "access",
	Path:       "path",
	UniqueAuth: "unique_auth",
	IsDel:      "is_del",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	Operator:   "operator",
}

// NewSystemMenusDao creates and returns a new DAO object for table data access.
func NewSystemMenusDao() *SystemMenusDao {
	return &SystemMenusDao{
		group:   "default",
		table:   "test_system_menus",
		columns: systemMenusColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SystemMenusDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SystemMenusDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SystemMenusDao) Columns() SystemMenusColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SystemMenusDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SystemMenusDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SystemMenusDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
