
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  # dao生成
  gen:
    dao:
      - link: "mysql:root:ZhjySG>p(2pS@tcp(8.134.148.139:3306)/test"
        removePrefix: "test_"
        descriptionTag: true
        noModelComment: true
