
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  # dao生成
  gen:
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/myshop"
        removePrefix: "my_"
        descriptionTag: true
        noModelComment: true
