// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"goframe/internal/model/system"

	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IRoute interface {
		AddRoute(routes ...system.RouteItem)
		InitModule(module string, isBool bool)
		Middleware(group *ghttp.RouterGroup, isAuth bool, isReset bool)
	}
)

var (
	localRoute IRoute
)

func Route() IRoute {
	if localRoute == nil {
		panic("implement not found for interface IRoute, forgot register?")
	}
	return localRoute
}

func RegisterRoute(i IRoute) {
	localRoute = i
}
