// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe/api/v1/backend/setting/rabc"
	"goframe/api/v1/backend/setting/system"
	"goframe/internal/model/entity"
	"goframe/internal/model/setting"
)

type (
	IRabcAdmin interface {
		List(ctx context.Context, input *rabc.AdminListReq) (total int, out []entity.MuRabcAdmin, err error)
		Add(ctx context.Context, input *rabc.AdminAddReq) (err error)
		Edit(ctx context.Context, input *rabc.AdminEditReq) (err error)
		Login(ctx context.Context, input *rabc.AdminLoginReq) (out *rabc.AdminLoginRes, err error)
		Logout(ctx context.Context) (err error)
	}
	IRabcMenu interface {
		List(ctx context.Context, input *rabc.MenuListReq) (out []setting.MenuListItem, err error)
		GetMenuItem(ctx context.Context, list []setting.MenuListItem) (res []setting.MenuListItem)
		Add(ctx context.Context, req *rabc.MenuAddReq) (err error)
		Edit(ctx context.Context, req *rabc.MenuEditReq) (err error)
		GetAllUniquePath(ctx context.Context) (uniqueAuthList []string, err error)
	}
	IRabcRoute interface {
		List(ctx context.Context, input *rabc.RouteListReq) (total int, out []entity.MuRabcRoute, err error)
		Add(ctx context.Context, req *rabc.RouteAddReq) (err error)
		Edit(ctx context.Context, req *rabc.RouteEditReq) (err error)
	}
	ISystemConfig interface {
		List(ctx context.Context, input *system.BasicConfigListReq) (total int, out []setting.SystemConfigRes, err error)
		Add(ctx context.Context, req *system.BasicConfigAddReq) (err error)
		Edit(ctx context.Context, input *system.BasicConfigEditReq) (err error)
		GetOne(ctx context.Context, id uint64) (out *system.SystemConfigOneRes, err error)
	}
)

var (
	localRabcRoute    IRabcRoute
	localSystemConfig ISystemConfig
	localRabcAdmin    IRabcAdmin
	localRabcMenu     IRabcMenu
)

func RabcAdmin() IRabcAdmin {
	if localRabcAdmin == nil {
		panic("implement not found for interface IRabcAdmin, forgot register?")
	}
	return localRabcAdmin
}

func RegisterRabcAdmin(i IRabcAdmin) {
	localRabcAdmin = i
}

func RabcMenu() IRabcMenu {
	if localRabcMenu == nil {
		panic("implement not found for interface IRabcMenu, forgot register?")
	}
	return localRabcMenu
}

func RegisterRabcMenu(i IRabcMenu) {
	localRabcMenu = i
}

func RabcRoute() IRabcRoute {
	if localRabcRoute == nil {
		panic("implement not found for interface IRabcRoute, forgot register?")
	}
	return localRabcRoute
}

func RegisterRabcRoute(i IRabcRoute) {
	localRabcRoute = i
}

func SystemConfig() ISystemConfig {
	if localSystemConfig == nil {
		panic("implement not found for interface ISystemConfig, forgot register?")
	}
	return localSystemConfig
}

func RegisterSystemConfig(i ISystemConfig) {
	localSystemConfig = i
}
