// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe/api/v1/backend/system/auths"
	"goframe/internal/model/system"

	"github.com/gogf/gf/v2/database/gdb"
)

type (
	IAuthsAdmin interface {
		List(ctx context.Context, input *auths.AdminListReq) (total int, out []system.SystemAdminListOut, err error)
		Query(input *auths.AdminListReq) *gdb.Model
		Add(ctx context.Context, input *auths.AdminAddReq) (err error)
		IsExitsUser(ctx context.Context, id uint, name string) (err error)
		Edit(ctx context.Context, input *auths.AdminEditReq) (err error)
		Login(ctx context.Context, input *auths.AdminLoginReq) (out *auths.AdminLoginRes, err error)
		Logout(ctx context.Context) (err error)
	}
	IAuthsMenu interface {
		List(ctx context.Context, input *auths.MenuListReq) (out auths.MenuListRes, err error)
		GetMenuItem(ctx context.Context, list []system.MenuListItem) (res []system.MenuListItem)
		Add(ctx context.Context, req *auths.MenuAddReq) (err error)
		Edit(ctx context.Context, req *auths.MenuEditReq) (err error)
		UniqueAuthList(ctx context.Context, input *auths.MenuUniqueAuthListReq) (out []string, err error)
		TreeList(ctx context.Context, req *auths.MenuTreeListReq) (out []system.MenuTreeListItem, err error)
		TreeListItem(ctx context.Context, list []system.MenuTreeListItem) (out []system.MenuTreeListItem, err error)
	}
	IAuthsRoute interface {
		List(ctx context.Context, input *auths.RouteListReq) (total int, out []system.SystemRouteOut, err error)
		Query(ctx context.Context, input *auths.RouteListReq) *gdb.Model
		Add(ctx context.Context, req *auths.RouteAddReq) (err error)
		Edit(ctx context.Context, input *auths.RouteEditReq) (err error)
	}
)

var (
	localAuthsMenu  IAuthsMenu
	localAuthsRoute IAuthsRoute
	localAuthsAdmin IAuthsAdmin
)

func AuthsRoute() IAuthsRoute {
	if localAuthsRoute == nil {
		panic("implement not found for interface IAuthsRoute, forgot register?")
	}
	return localAuthsRoute
}

func RegisterAuthsRoute(i IAuthsRoute) {
	localAuthsRoute = i
}

func AuthsAdmin() IAuthsAdmin {
	if localAuthsAdmin == nil {
		panic("implement not found for interface IAuthsAdmin, forgot register?")
	}
	return localAuthsAdmin
}

func RegisterAuthsAdmin(i IAuthsAdmin) {
	localAuthsAdmin = i
}

func AuthsMenu() IAuthsMenu {
	if localAuthsMenu == nil {
		panic("implement not found for interface IAuthsMenu, forgot register?")
	}
	return localAuthsMenu
}

func RegisterAuthsMenu(i IAuthsMenu) {
	localAuthsMenu = i
}
