// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe/api/v1/backend/system/auths"
)

type (
	IAuthsAdmin interface {
		Login(ctx context.Context, input *auths.AdminLoginReq) (out *auths.AdminLoginRes, err error)
		Logout(ctx context.Context) (err error)
	}
	IAuthsMenu interface {
		Add(ctx context.Context, req *auths.MenuAddReq) (err error)
	}
)

var (
	localAuthsMenu  IAuthsMenu
	localAuthsAdmin IAuthsAdmin
)

func AuthsAdmin() IAuthsAdmin {
	if localAuthsAdmin == nil {
		panic("implement not found for interface IAuthsAdmin, forgot register?")
	}
	return localAuthsAdmin
}

func RegisterAuthsAdmin(i IAuthsAdmin) {
	localAuthsAdmin = i
}

func AuthsMenu() IAuthsMenu {
	if localAuthsMenu == nil {
		panic("implement not found for interface IAuthsMenu, forgot register?")
	}
	return localAuthsMenu
}

func RegisterAuthsMenu(i IAuthsMenu) {
	localAuthsMenu = i
}
