// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe/internal/dao/internal"
)

// internalMuRabcMenusDao is internal type for wrapping internal DAO implements.
type internalMuRabcMenusDao = *internal.MuRabcMenusDao

// muRabcMenusDao is the data access object for table mu_rabc_menus.
// You can define custom methods on it to extend its functionality as you wish.
type muRabcMenusDao struct {
	internalMuRabcMenusDao
}

var (
	// MuRabcMenus is globally public accessible object for table mu_rabc_menus operations.
	MuRabcMenus = muRabcMenusDao{
		internal.NewMuRabcMenusDao(),
	}
)

// Fill with you ideas below.
