// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe/internal/dao/internal"
)

// internalMuRabcRoleRouteDao is internal type for wrapping internal DAO implements.
type internalMuRabcRoleRouteDao = *internal.MuRabcRoleRouteDao

// muRabcRoleRouteDao is the data access object for table mu_rabc_role_route.
// You can define custom methods on it to extend its functionality as you wish.
type muRabcRoleRouteDao struct {
	internalMuRabcRoleRouteDao
}

var (
	// MuRabcRoleRoute is globally public accessible object for table mu_rabc_role_route operations.
	MuRabcRoleRoute = muRabcRoleRouteDao{
		internal.NewMuRabcRoleRouteDao(),
	}
)

// Fill with you ideas below.
