// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe/internal/dao/internal"
)

// internalMuRbacRoleDao is internal type for wrapping internal DAO implements.
type internalMuRbacRoleDao = *internal.MuRbacRoleDao

// muRbacRoleDao is the data access object for table mu_rbac_role.
// You can define custom methods on it to extend its functionality as you wish.
type muRbacRoleDao struct {
	internalMuRbacRoleDao
}

var (
	// MuRbacRole is globally public accessible object for table mu_rbac_role operations.
	MuRbacRole = muRbacRoleDao{
		internal.NewMuRbacRoleDao(),
	}
)

// Fill with you ideas below.
