// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe/internal/dao/internal"
)

// internalMuRabcAdminDao is internal type for wrapping internal DAO implements.
type internalMuRabcAdminDao = *internal.MuRabcAdminDao

// muRabcAdminDao is the data access object for table mu_rabc_admin.
// You can define custom methods on it to extend its functionality as you wish.
type muRabcAdminDao struct {
	internalMuRabcAdminDao
}

var (
	// MuRabcAdmin is globally public accessible object for table mu_rabc_admin operations.
	MuRabcAdmin = muRabcAdminDao{
		internal.NewMuRabcAdminDao(),
	}
)

// Fill with you ideas below.
