// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe/internal/dao/internal"
)

// internalMuRabcRouteDao is internal type for wrapping internal DAO implements.
type internalMuRabcRouteDao = *internal.MuRabcRouteDao

// muRabcRouteDao is the data access object for table mu_rabc_route.
// You can define custom methods on it to extend its functionality as you wish.
type muRabcRouteDao struct {
	internalMuRabcRouteDao
}

var (
	// MuRabcRoute is globally public accessible object for table mu_rabc_route operations.
	MuRabcRoute = muRabcRouteDao{
		internal.NewMuRabcRouteDao(),
	}
)

// Fill with you ideas below.
