// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe/internal/dao/internal"
)

// internalSystemAdminDao is internal type for wrapping internal DAO implements.
type internalSystemAdminDao = *internal.SystemAdminDao

// systemAdminDao is the data access object for table test_system_admin.
// You can define custom methods on it to extend its functionality as you wish.
type systemAdminDao struct {
	internalSystemAdminDao
}

var (
	// SystemAdmin is globally public accessible object for table test_system_admin operations.
	SystemAdmin = systemAdminDao{
		internal.NewSystemAdminDao(),
	}
)

// Fill with you ideas below.
