// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe/internal/dao/internal"
)

// internalSystemMenusDao is internal type for wrapping internal DAO implements.
type internalSystemMenusDao = *internal.SystemMenusDao

// systemMenusDao is the data access object for table test_system_menus.
// You can define custom methods on it to extend its functionality as you wish.
type systemMenusDao struct {
	internalSystemMenusDao
}

var (
	// SystemMenus is globally public accessible object for table test_system_menus operations.
	SystemMenus = systemMenusDao{
		internal.NewSystemMenusDao(),
	}
)

// Fill with you ideas below.
