// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe/internal/dao/internal"
)

// internalSystemRouteDao is internal type for wrapping internal DAO implements.
type internalSystemRouteDao = *internal.SystemRouteDao

// systemRouteDao is the data access object for table test_system_route.
// You can define custom methods on it to extend its functionality as you wish.
type systemRouteDao struct {
	internalSystemRouteDao
}

var (
	// SystemRoute is globally public accessible object for table test_system_route operations.
	SystemRoute = systemRouteDao{
		internal.NewSystemRouteDao(),
	}
)

// Fill with you ideas below.
