// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MuRabcRoute is the golang structure for table mu_rabc_route.
type MuRabcRoute struct {
	Id        uint        `json:"id"        description:"ID"`
	MenuId    uint        `json:"menuId"    description:"菜单ID"`
	Name      string      `json:"name"      description:"名称"`
	Method    string      `json:"method"    description:"提交方式POST GET PUT DELETE"`
	Path      string      `json:"path"      description:"路径"`
	Status    int         `json:"status"    description:"是否隐藏菜单 0隐藏 1显示"`
	Sort      int         `json:"sort"      description:"排序"`
	Operator  string      `json:"operator"  description:"操作人"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
}
