// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MuRabcRoleRoute is the golang structure for table mu_rabc_role_route.
type MuRabcRoleRoute struct {
	Id        uint        `json:"id"        description:"ID"`
	RouteId   uint        `json:"routeId"   description:"路由ID"`
	RoleId    int         `json:"roleId"    description:"角色ID"`
	Operator  string      `json:"operator"  description:"操作人"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
}
