// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MuRbacRole is the golang structure for table mu_rbac_role.
type MuRbacRole struct {
	Id          uint        `json:"id"          description:""`
	Name        string      `json:"name"        description:"名称"`
	Description string      `json:"description" description:"描述"`
	Operator    string      `json:"operator"    description:"操作人"`
	CreateTime  *gtime.Time `json:"createTime"  description:"创建时间"`
	UpdateTime  *gtime.Time `json:"updateTime"  description:"更新时间"`
}
