// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MuRabcMenus is the golang structure for table mu_rabc_menus.
type MuRabcMenus struct {
	Id         uint        `json:"id"         description:"菜单ID"`
	Pid        uint        `json:"pid"        description:"父级id"`
	Icon       string      `json:"icon"       description:"图标"`
	Title      string      `json:"title"      description:"名称"`
	Sort       int         `json:"sort"       description:"排序"`
	IsShow     int         `json:"isShow"     description:"是否隐藏菜单 0隐藏 1显示"`
	Path       string      `json:"path"       description:"路径"`
	Operator   string      `json:"operator"   description:"操作人"`
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:"更新时间"`
	CreatedAt  *gtime.Time `json:"createdAt"  description:"创建时间"`
	Header     string      `json:"header"     description:"名称"`
	IsHeader   int         `json:"isHeader"   description:"名称"`
	UniqueAuth string      `json:"uniqueAuth" description:"名称"`
}
