// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SystemConfig is the golang structure for table system_config.
type SystemConfig struct {
	Id        uint        `json:"id"        description:"ID"`
	Name      string      `json:"name"      description:"名称"`
	Type      int         `json:"type"      description:"0json配置1基础配置2商城配置3用户配置"`
	Config    string      `json:"config"    description:"配置"`
	Operator  string      `json:"operator"  description:"操作人"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
}
